baseurl = ""
languageCode = "en-us"
title = "Co-Worker"
theme = "hugo-strata-theme"
disqusShortname = "spf13"
publishdir = "docs"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Your name"
	description = "Describe your website"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "11.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**We're Co-worker,**<br> winter clothes sales company<br> in Korea Aerospace University.<br> Crafted by [HTML5 UP](//html5up.net)."

		copyright = [
			"&copy; Hyunsung Lee",
			"Design: [HTML5 UP](//html5up.net)",
			"Demo Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		hide  = false
		title = "Ipsum lorem dolor aliquam ante commodo magna sed accumsan arcu neque."
		content = "Accumsan orci faucibus id eu lorem semper. Eu ac iaculis ac nunc nisi lorem vulputate lorem neque cubilia ac in adipiscing in curae lobortis tortor primis integer massa adipiscing id nisi accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque cubilia."


	[params.portfolio]
		hide  = false
		title = "All clothes"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "2/1.jpg"
			thumb = "1/1.jpg"
			title = "Black stripe knit. - size: L(100)"
			description = "~~35,000~~ 20,000 won"

		[[params.portfolio.gallery]]
			image = "2/4.jpg"
			thumb = "1/4.jpg"
			title = "Black open kara shirt. - size: L(100)"
			description = "~~20,000~~ 13,000 won"

		[[params.portfolio.gallery]]
			image = "2/2.jpg"
			thumb = "1/2.jpg"
			title = "Blue painting shirt. - size: L(100)"
			description = "~~15,000~~ 10,000 won"

		[[params.portfolio.gallery]]
			image = "2/3.jpg"
			thumb = "1/3.jpg"
			title = "Black padding jumper. - size: L(100)"
			description = "~~55,000~~ 40,000 won"

		[[params.portfolio.gallery]]
			image = "2/5.jpg"
			thumb = "1/5.jpg"
			title = "Black stripe pants. - size: M(30)"
			description = "~~25,000~~ 18,000 won"

	[params.recentposts]
		hide  = true
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "If you want to buy some clothes, please contact here."

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = "39.7889055,-120.5443524"
		address = [
			"541-021320-01-016 ",
			"IBK kiupbank ",
			"Lee Hyun Sung "
		]
		phone = "010-3075-4373"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "candyhr@naver.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "All"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "Outer"
	url  = "/seminar/"
	weight = 0
